version: 2
jobs:
    build:
        docker:
            - image: dockercore/golang-cross:1.12.0

        working_directory: /go/src/github.com/mah0x211/mixdown
        steps:
            - run:
                  name: Install golangci-lint
                  command: go get -u github.com/golangci/golangci-lint/cmd/golangci-lint

            - checkout

            - run:
                  name: Test
                  command: make test

            - run:
                  name: Lint
                  command: make lint

            - run:
                  name: Build linux
                  command: make build-linux

            - run:
                  name: Build darwin
                  command: make build-darwin

            - run:
                  name: Cleanup dependencies
                  when: always
                  command: rm -rf ./build/deps

            - store_artifacts:
                  path: ./build
                  destination: release

            - deploy:
                  command: |
                      sh ./autorelease.sh
